package com.moyun.poetry.ui.atmosphere

import androidx.compose.ui.graphics.Color

/**
 * 对齐 Web `lib/theme-map.ts` 的 22 套主题签名。
 * 色值取自 CSS 主渐变与 accent/glow，供 Compose 重绘。
 */
object ThemeMap {

    private fun c(hex: Long, a: Float = 1f): Color {
        val r = ((hex shr 16) and 0xFF) / 255f
        val g = ((hex shr 8) and 0xFF) / 255f
        val b = (hex and 0xFF) / 255f
        return Color(r, g, b, a)
    }

    private fun rgba(r: Int, g: Int, b: Int, a: Float): Color =
        Color(r / 255f, g / 255f, b / 255f, a)

    val all: Map<String, ThemeVisual> = mapOf(
        "night-moon" to ThemeVisual(
            id = "night-moon",
            label = "夜月",
            baseTop = c(0x050508),
            baseMid = c(0x0d1118),
            baseBottom = c(0x1a1a1a),
            accent = c(0xc8d0e0),
            glow = rgba(220, 230, 255, 0.28f),
            glowSpots = listOf(
                GlowSpot(0.70f, 0.20f, 0.55f, rgba(180, 190, 220, 0.20f)),
                GlowSpot(0.30f, 0.80f, 0.45f, rgba(52, 73, 94, 0.38f)),
            ),
            moon = MoonForm.DEFAULT,
            mist = MistLevel.SOFT,
            clouds = CloudForm.HIGH,
            mountains = MountainForm.DISTANT,
            particles = ParticleMode.STARS,
            particleSafeCenter = true,
            particleDensity = 0.72f,
        ),
        "dawn-dusk" to ThemeVisual(
            id = "dawn-dusk",
            label = "晨昏",
            baseTop = c(0x120810),
            baseMid = c(0x1a1014),
            baseBottom = c(0x1a1a1a),
            accent = c(0xe0b898),
            glow = rgba(200, 120, 70, 0.24f),
            glowSpots = listOf(
                GlowSpot(0.22f, 0.78f, 0.50f, rgba(200, 100, 50, 0.28f)),
                GlowSpot(0.70f, 0.30f, 0.42f, rgba(120, 60, 100, 0.18f)),
            ),
            sun = SunForm.LOW,
            mist = MistLevel.SOFT,
            clouds = CloudForm.BAND,
            mountains = MountainForm.PEAKS,
        ),
        "spring" to ThemeVisual(
            id = "spring",
            label = "春",
            baseTop = c(0x0b100e),
            baseMid = c(0x101612),
            baseBottom = c(0x1a1a1a),
            accent = c(0xc8d4b8),
            glow = rgba(170, 200, 150, 0.14f),
            glowSpots = listOf(
                GlowSpot(0.30f, 0.25f, 0.42f, rgba(200, 160, 170, 0.10f)),
                GlowSpot(0.55f, 0.70f, 0.48f, rgba(90, 130, 85, 0.20f)),
            ),
            mist = MistLevel.SOFT,
            clouds = CloudForm.HIGH,
            mountains = MountainForm.DISTANT,
            petals = true,
            particles = ParticleMode.PETALS,
            particleSafeCenter = true,
            particleDensity = 0.38f,
        ),
        "summer" to ThemeVisual(
            id = "summer",
            label = "夏",
            baseTop = c(0x0a120c),
            baseMid = c(0x101810),
            baseBottom = c(0x1a1a1a),
            accent = c(0xb8d0a0),
            glow = rgba(200, 170, 80, 0.16f),
            glowSpots = listOf(
                GlowSpot(0.78f, 0.14f, 0.40f, rgba(220, 180, 70, 0.18f)),
                GlowSpot(0.30f, 0.70f, 0.48f, rgba(40, 90, 50, 0.18f)),
            ),
            sun = SunForm.HIGH,
            mountains = MountainForm.DISTANT,
            particles = ParticleMode.FIREFLY,
            particleSafeCenter = true,
            particleDensity = 1.05f,
        ),
        "autumn" to ThemeVisual(
            id = "autumn",
            label = "秋",
            baseTop = c(0x100c08),
            baseMid = c(0x16120e),
            baseBottom = c(0x1a1a1a),
            accent = c(0xd4b898),
            glow = rgba(180, 120, 60, 0.18f),
            glowSpots = listOf(
                GlowSpot(0.60f, 0.38f, 0.48f, rgba(140, 80, 40, 0.22f)),
                GlowSpot(0.50f, 0.88f, 0.42f, rgba(80, 50, 30, 0.20f)),
            ),
            mist = MistLevel.SOFT,
            mountains = MountainForm.RANGE,
            horizon = HorizonForm.PLAIN,
            particles = ParticleMode.LEAVES,
            particleSafeCenter = true,
            particleDensity = 0.9f,
        ),
        "winter" to ThemeVisual(
            id = "winter",
            label = "冬",
            baseTop = c(0x0a0e12),
            baseMid = c(0x101418),
            baseBottom = c(0x1a1a1a),
            accent = c(0xc0ccd8),
            glow = rgba(160, 180, 200, 0.15f),
            glowSpots = listOf(
                GlowSpot(0.50f, 0.30f, 0.48f, rgba(180, 200, 220, 0.12f)),
            ),
            mist = MistLevel.SOFT,
            mountains = MountainForm.JAGGED,
            snow = true,
            particles = ParticleMode.SNOW,
            particleSafeCenter = true,
            particleDensity = 0.48f,
        ),
        "snow-river" to ThemeVisual(
            id = "snow-river",
            label = "寒江",
            baseTop = c(0x0a1018),
            baseMid = c(0x121820),
            baseBottom = c(0x1a1a1a),
            accent = c(0xb8c8d8),
            glow = rgba(180, 200, 220, 0.20f),
            glowSpots = listOf(
                GlowSpot(0.50f, 0.30f, 0.48f, rgba(200, 220, 240, 0.12f)),
            ),
            mist = MistLevel.SOFT,
            mountains = MountainForm.JAGGED,
            horizon = HorizonForm.FROST,
            boat = true,
            particles = ParticleMode.SNOW,
            particleSafeCenter = true,
            particleDensity = 0.32f,
        ),
        "rain" to ThemeVisual(
            id = "rain",
            label = "烟雨",
            baseTop = c(0x0a0e12),
            baseMid = c(0x0e1318),
            baseBottom = c(0x1a1a1a),
            accent = c(0xa8b8c8),
            glow = rgba(100, 120, 140, 0.16f),
            glowSpots = listOf(
                GlowSpot(0.50f, 0.15f, 0.52f, rgba(100, 120, 145, 0.14f)),
                GlowSpot(0.40f, 0.75f, 0.45f, rgba(60, 75, 90, 0.18f)),
            ),
            mist = MistLevel.HEAVY,
            clouds = CloudForm.BAND,
            rain = true,
            mountains = MountainForm.RANGE,
        ),
        "mountain" to ThemeVisual(
            id = "mountain",
            label = "山岳",
            baseTop = c(0x07090d),
            baseMid = c(0x0c1016),
            baseBottom = c(0x1a1a1a),
            accent = c(0xa8b4c0),
            glow = rgba(90, 110, 135, 0.16f),
            glowSpots = listOf(
                GlowSpot(0.50f, 0.18f, 0.40f, rgba(70, 90, 120, 0.10f)),
                GlowSpot(0.50f, 0.88f, 0.48f, rgba(30, 40, 52, 0.50f)),
            ),
            mist = MistLevel.SOFT,
            clouds = CloudForm.HIGH,
            mountains = MountainForm.PEAKS,
        ),
        "river-lake" to ThemeVisual(
            id = "river-lake",
            label = "江湖",
            baseTop = c(0x080c10),
            baseMid = c(0x0c1218),
            baseBottom = c(0x1a1a1a),
            accent = c(0xa0b8c8),
            glow = rgba(70, 110, 140, 0.18f),
            glowSpots = listOf(
                GlowSpot(0.50f, 0.85f, 0.50f, rgba(40, 70, 90, 0.30f)),
            ),
            mist = MistLevel.SOFT,
            mountains = MountainForm.RANGE,
            horizon = HorizonForm.WATER,
            ripples = true,
            boat = true,
        ),
        "pastoral" to ThemeVisual(
            id = "pastoral",
            label = "田园",
            baseTop = c(0x0a0e12),
            baseMid = c(0x0e1410),
            baseBottom = c(0x1a1a1a),
            accent = c(0xc4d0b0),
            glow = rgba(140, 170, 120, 0.16f),
            glowSpots = listOf(
                GlowSpot(0.72f, 0.18f, 0.40f, rgba(190, 205, 230, 0.14f)),
                GlowSpot(0.50f, 0.78f, 0.45f, rgba(70, 100, 50, 0.22f)),
            ),
            mist = MistLevel.SOFT,
            fields = true,
            mountains = MountainForm.ROLLING,
            particles = ParticleMode.FIREFLY,
            particleSafeCenter = true,
            particleDensity = 0.85f,
        ),
        "frontier" to ThemeVisual(
            id = "frontier",
            label = "边塞",
            baseTop = c(0x100c08),
            baseMid = c(0x14100c),
            baseBottom = c(0x1a1a1a),
            accent = c(0xd0b890),
            glow = rgba(160, 120, 60, 0.16f),
            glowSpots = listOf(
                GlowSpot(0.50f, 0.72f, 0.48f, rgba(140, 100, 50, 0.16f)),
                GlowSpot(0.78f, 0.18f, 0.35f, rgba(180, 170, 140, 0.06f)),
            ),
            mist = MistLevel.SOFT,
            mountains = MountainForm.JAGGED,
            horizon = HorizonForm.PLAIN,
            particles = ParticleMode.STARS_FRONTIER,
            particleSafeCenter = true,
            particleDensity = 0.85f,
        ),
        "flowers" to ThemeVisual(
            id = "flowers",
            label = "花意",
            baseTop = c(0x12080c),
            baseMid = c(0x160e12),
            baseBottom = c(0x1a1a1a),
            accent = c(0xe8b8c4),
            glow = rgba(210, 100, 130, 0.22f),
            glowSpots = listOf(
                GlowSpot(0.28f, 0.32f, 0.42f, rgba(200, 90, 120, 0.20f)),
                GlowSpot(0.78f, 0.58f, 0.36f, rgba(180, 70, 100, 0.12f)),
                GlowSpot(0.50f, 1.00f, 0.40f, rgba(60, 24, 36, 0.35f)),
            ),
            mountains = MountainForm.NONE,
            petals = true,
            particles = ParticleMode.PETALS,
            particleSafeCenter = true,
            particleDensity = 0.75f,
        ),
        "birds" to ThemeVisual(
            id = "birds",
            label = "禽鸟",
            baseTop = c(0x0c1218),
            baseMid = c(0x0e1416),
            baseBottom = c(0x1a1a1a),
            accent = c(0xc8d6e0),
            glow = rgba(150, 175, 200, 0.12f),
            glowSpots = listOf(
                GlowSpot(0.50f, 0.12f, 0.50f, rgba(160, 185, 210, 0.16f)),
            ),
            mist = MistLevel.SOFT,
            mountains = MountainForm.DISTANT,
            birds = true,
        ),
        "fish-aquatic" to ThemeVisual(
            id = "fish-aquatic",
            label = "鱼藻",
            baseTop = c(0x060e10),
            baseMid = c(0x0a1416),
            baseBottom = c(0x1a1a1a),
            accent = c(0x98c0c0),
            glow = rgba(50, 120, 130, 0.20f),
            glowSpots = listOf(
                GlowSpot(0.50f, 0.80f, 0.50f, rgba(30, 80, 90, 0.32f)),
            ),
            mist = MistLevel.SOFT,
            mountains = MountainForm.NONE,
            horizon = HorizonForm.WATER,
            ripples = true,
        ),
        "trees-bamboo" to ThemeVisual(
            id = "trees-bamboo",
            label = "竹木",
            baseTop = c(0x080e0a),
            baseMid = c(0x0e1410),
            baseBottom = c(0x1a1a1a),
            accent = c(0xa8c4a8),
            glow = rgba(60, 100, 70, 0.15f),
            glowSpots = listOf(
                GlowSpot(0.20f, 0.50f, 0.48f, rgba(40, 70, 45, 0.25f)),
            ),
            mist = MistLevel.SOFT,
            bamboo = true,
            mountains = MountainForm.NONE,
        ),
        "wine" to ThemeVisual(
            id = "wine",
            label = "对酒",
            baseTop = c(0x0e0909),
            baseMid = c(0x14100e),
            baseBottom = c(0x1a1a1a),
            accent = c(0xe0b098),
            glow = rgba(220, 130, 85, 0.38f),
            glowSpots = listOf(
                GlowSpot(0.50f, 0.52f, 0.38f, rgba(178, 58, 72, 0.32f)),
                GlowSpot(0.50f, 0.58f, 0.48f, rgba(220, 150, 80, 0.16f)),
                GlowSpot(0.50f, 1.00f, 0.48f, rgba(50, 22, 18, 0.48f)),
            ),
            mountains = MountainForm.NONE,
        ),
        "festival" to ThemeVisual(
            id = "festival",
            label = "华灯",
            baseTop = c(0x08060a),
            baseMid = c(0x100c10),
            baseBottom = c(0x1a1a1a),
            accent = c(0xe0c0a0),
            glow = rgba(200, 140, 80, 0.22f),
            glowSpots = listOf(
                GlowSpot(0.50f, 0.60f, 0.38f, rgba(178, 58, 72, 0.15f)),
                GlowSpot(0.70f, 0.40f, 0.30f, rgba(200, 160, 80, 0.10f)),
            ),
            lanterns = true,
            mountains = MountainForm.NONE,
        ),
        "homesickness" to ThemeVisual(
            id = "homesickness",
            label = "思乡",
            baseTop = c(0x07080c),
            baseMid = c(0x0c0e14),
            baseBottom = c(0x1a1a1a),
            accent = c(0xc0c8d8),
            glow = rgba(140, 160, 190, 0.12f),
            glowSpots = listOf(
                GlowSpot(0.78f, 0.16f, 0.36f, rgba(160, 170, 200, 0.08f)),
            ),
            mist = MistLevel.SOFT,
            clouds = CloudForm.HIGH,
            mountains = MountainForm.NONE,
            particles = ParticleMode.STARS,
            particleSafeCenter = true,
            particleDensity = 0.12f,
        ),
        "parting" to ThemeVisual(
            id = "parting",
            label = "离别",
            baseTop = c(0x0e0a0a),
            baseMid = c(0x121010),
            baseBottom = c(0x1a1a1a),
            accent = c(0xd0b8a8),
            glow = rgba(140, 100, 80, 0.14f),
            glowSpots = listOf(
                GlowSpot(0.50f, 0.78f, 0.42f, rgba(90, 70, 60, 0.14f)),
            ),
            mist = MistLevel.SOFT,
            clouds = CloudForm.HIGH,
            mountains = MountainForm.DISTANT,
            horizon = HorizonForm.PLAIN,
        ),
        "reclusion" to ThemeVisual(
            id = "reclusion",
            label = "隐逸",
            baseTop = c(0x090c0a),
            baseMid = c(0x0e1210),
            baseBottom = c(0x1a1a1a),
            accent = c(0xb0c0b0),
            glow = rgba(80, 100, 85, 0.12f),
            glowSpots = listOf(
                GlowSpot(0.40f, 0.50f, 0.45f, rgba(50, 70, 55, 0.15f)),
            ),
            mist = MistLevel.SOFT,
            clouds = CloudForm.BAND,
            mountains = MountainForm.RANGE,
            bamboo = true,
        ),
        "landscape" to ThemeVisual(
            id = "landscape",
            label = "山水",
            baseTop = c(0x090b0f),
            baseMid = c(0x0f1318),
            baseBottom = c(0x1a1a1a),
            accent = c(0xb0bcc8),
            glow = rgba(90, 110, 130, 0.18f),
            glowSpots = listOf(
                GlowSpot(0.50f, 0.90f, 0.52f, rgba(45, 55, 65, 0.45f)),
            ),
            mist = MistLevel.SOFT,
            clouds = CloudForm.SEA,
            mountains = MountainForm.DISTANT,
        ),
    )

    fun get(theme: String): ThemeVisual =
        all[theme] ?: all.getValue("landscape")
}
